## Requests Import

In [ ]:
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
from bs4.element import NavigableString

## Selenium Import

In [ ]:
!pip install selenium
!apt-get update
!apt install chromium-chromedriver

from selenium import webdriver
from urllib.request import urlopen
from bs4 import BeautifulSoup as bs
from urllib.parse import quote_plus
from selenium.webdriver.common.keys import Keys
import time
from urllib.request import urlopen

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', chrome_options=chrome_options)

Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from selenium) (1.24.3)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,755 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,202 kB]
Fetched 5,213 kB in 2s (2,120 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-chromedriver is already the newest version (92.0.4515.159-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: DeprecationWarning: use options instead of chrome_options

## KB차차차 메인홈페이지 크롤링

In [ ]:
requests.get('https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page=1&sort=-orderDate')

In [ ]:
driver.get('https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page=1&sort=-orderDate')

In [ ]:
for i in range(0, 2):
  url = f'https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page={i}&sort=-orderDate'
  driver.get(url)
  soup = BeautifulSoup(driver.page_source, 'html.parser')

  print(f'------------ page {i + 1} ------------')
  print("\n") 

  # 인증 및 진단 매물
  print("인증 및 진단 매물")
  print("--------------------------------------------------------")
  for j in range(1, 100):
    name_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.tit'
    name = soup.select(name_selector)
    if not name :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in name[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('모델명 :', text)

    date_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.first'
    date = soup.select(date_selector)
    if not date :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in date[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('연식 :', text)

    km_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.data-in > span'
    km = soup.select(km_selector)
    if not km :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in km[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('주행거리 :', text)

    region_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.data-in > span:nth-of-type(2)'
    region = soup.select(region_selector)
    if not region :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in region[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('지역 :', text)

    pay_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.pay'
    pay = soup.select(pay_selector)
    if not pay :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in pay[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('가격 :', text, '만원')
    print("\n") 

  print("\n") 
  
  # 추천 매물
  print("추천 매물")
  print("--------------------------------------------------------")
  for j in range(1, 100):
    name_selector = f'div.__used-car-list > div:nth-of-type(2) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.tit'
    name = soup.select(name_selector)
    if not name:
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in name[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('모델명 :', text)

    date_selector = f'div.__used-car-list > div:nth-of-type(2) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.first'
    date = soup.select(date_selector)
    if not date :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in date[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('연식 :', text)

    km_selector = f'div.__used-car-list > div:nth-of-type(2) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.data-in > span'
    km = soup.select(km_selector)
    if not km :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in km[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('주행거리 :', text)

    region_selector = f'div.__used-car-list > div:nth-of-type(2) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > div.data-line.tp03 > div.data-in > span:nth-of-type(2)'
    region = soup.select(region_selector)
    if not region :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in region[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('지역 :', text)

    pay_selector = f'div.__used-car-list > div:nth-of-type(2) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.pay'
    pay = soup.select(pay_selector)
    if not pay :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in pay[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('가격 :', text)
    print("\n") 

  print("\n")
  # 일반 매물
  print("일반 매물")
  print("--------------------------------------------------------")
  for j in range(1, 100):
    name_selector = f'div.__used-car-list > div.cs-list02.cs-list02--ratio.small-tp.generalRegist > div.list-in > div:nth-of-type({j}) > div.con > div > a > strong.tit'
    name = soup.select(name_selector)
    if not name:
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in name[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('모델명 :', text)

    date_selector = f'div.__used-car-list > div.cs-list02.cs-list02--ratio.small-tp.generalRegist > div.list-in > div:nth-of-type({j}) > div.con > .item > a.link > div.data-line.tp03 > div.first'
    date = soup.select(date_selector)
    if not date :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in date[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('연식 :', text)

    km_selector = f'div.__used-car-list > div.cs-list02.cs-list02--ratio.small-tp.generalRegist > div.list-in > div:nth-of-type({j}) > div.con > .item > a.link > div.data-line.tp03 > div.data-in > span'
    km = soup.select(km_selector)
    if not km :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in km[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('주행거리 :', text)

    region_selector = f'div.__used-car-list > div.cs-list02.cs-list02--ratio.small-tp.generalRegist > div.list-in > div:nth-of-type({j}) > div.con > .item > a.link > div.data-line.tp03 > div.data-in > span:nth-of-type(2)'
    region = soup.select(region_selector)
    if not region :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in region[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('지역 :', text)

    pay_selector = f'div.__used-car-list > div.cs-list02.cs-list02--ratio.small-tp.generalRegist > div.list-in > div:nth-of-type({j}) > div.con > .item > a.link > strong.pay'
    pay = soup.select(pay_selector)
    if not pay :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in pay[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('가격 :', text)
    print("\n")

------------ page 1 ------------


인증 및 진단 매물
--------------------------------------------------------
모델명 : 기아 더 K9 3.8 GDI 플래티넘 I
연식 : 2019년 05월 (19년식)
주행거리 : 23,000km
지역 : 경기
가격 : 3,800 만원


모델명 : 제네시스 G90 3.8 GDi AWD 프레스티지
연식 : 2020년 04월 (20년식)
주행거리 : 17,553km
지역 : 대구
가격 : 9,250 만원


모델명 : 현대 그랜저IG 3.0 익스클루시브 기본형
연식 : 2016년 11월 (17년식)
주행거리 : 62,000km
지역 : 경기
가격 : 2,020 만원


모델명 : 쌍용 G4 렉스턴 2.2 4WD 유라시아 에디션
연식 : 2018년 06월 (18년식)
주행거리 : 36,392km
지역 : 인천
가격 : 2,590 만원


모델명 : 제네시스 G70 2.2D Supreme
연식 : 2018년 08월 (18년식)
주행거리 : 69,337km
지역 : 경기
가격 : 3,050 만원




추천 매물
--------------------------------------------------------
모델명 : 기아 K5 하이브리드 2세대 2.0 노블레스
연식 : 2018년 04월 (18년식)
주행거리 : 35,475km
지역 : 대구
가격 : 2,080만원


모델명 : 현대 갤로퍼2 숏보디 이노베이션 터보
연식 : 2003년 07월 (03년식)
주행거리 : 127,400km
지역 : 경기
가격 : 490만원


모델명 : 현대 아반떼MD M16 GDi LUXURY
연식 : 2011년 01월 (11년식)
주행거리 : 96,000km
지역 : 대구
가격 : 599만원


모델명 : 현대 그랜저HG HG300 프라임
연식 : 2013년 03월 (13년식)
주행거리 : 154,100km
지역 : 서울
가격 : 980만원


모델명 : 현대 쏘나타 뉴 라이즈 2.0 스마트 스페셜
연식 : 2018년 07월 (19년식)
주행거리 : 28,067km
지역 : 경기
가격 : 1,950만원




일반 매물
--------------------------------------------------------
모델명 : 르노삼성 뉴SM5 LPLi LE
연식 : 2007년 01월 (07년식)
주행거리 : 167,859km
지역 : 경기
가격 : 180만원


모델명 : 현대 싼타페 2.0 디젤 2WD GOLD 고급형
연식 : 2001년 07월 (01년식)
주행거리 : 193,659km
지역 : 경기
가격 : 190만원


모델명 : 현대 그랜드스타렉스 12인승 왜건 CVX 럭셔리
연식 : 2007년 08월 (08년식)
주행거리 : 149,316km
지역 : 서울
가격 : 690만원


모델명 : 현대 그랜저HG HG300 노블
연식 : 2011년 03월 (11년식)
주행거리 : 111,783km
지역 : 경기
가격 : 1,129만원


모델명 : 현대 싼타페 DM R2.2 2WD PREMIUM
연식 : 2014년 02월 (14년식)
주행거리 : 114,992km
지역 : 경기
가격 : 1,549만원


모델명 : 르노삼성 SM6 1.5 dCi SE
연식 : 2016년 11월 (16년식)
주행거리 : 58,158km
지역 : 경기
가격 : 1,599만원


모델명 : 기아 봉고3 1톤 냉동탑차 초장축 경제형 킹캡 디럭스
연식 : 2015년 01월 (15년식)
주행거리 : 188,707km
지역 : 경남
가격 : 870만원


모델명 : 기아 그랜드카니발 GLX 월드스페셜
연식 : 2005년 08월 (06년식)
주행거리 : 257,561km
지역 : 부산
가격 : 299만원


모델명 : 기아 아벨라 델타 1.3 Si
연식 : 1997년 06월 (97년식)
주행거리 : 160,034km
지역 : 경남
가격 : 200만원


모델명 : 기아 그랜드카니발 GLX 월드스페셜
연식 : 2009년 10월 (10년식)
주행거리 : 164,812km
지역 : 서울
가격 : 790만원


모델명 : 현대 그랜저TG Q270 Luxury 기본형
연식 : 2006년 10월 (07년식)
주행거리 : 155,827km
지역 : 경기
가격 : 270만원


모델명 : 현대 뉴카운티 장축 GOLD 25인승 자가용
연식 : 2014년 02월 (14년식)
주행거리 : 134,000km
지역 : 광주
가격 : 2,999만원


모델명 : 쌍용 코란도C 클러비 2WD 파크
연식 : 2013년 01월 (13년식)
주행거리 : 185,410km
지역 : 대구
가격 : 530만원


모델명 : 현대 더 뉴 아반떼 1.6 GDi 모던 기본형
연식 : 2013년 08월 (14년식)
주행거리 : 54,734km
지역 : 대구
가격 : 750만원


모델명 : 현대 투싼ix 디젤 2WD X20 럭셔리
연식 : 2010년 04월 (11년식)
주행거리 : 128,634km
지역 : 대구
가격 : 699만원


모델명 : 기아 올 뉴 카니발 9인승 2.2 디젤 하이리무진 럭셔리
연식 : 2015년 04월 (15년식)
주행거리 : 93,228km
지역 : 경남
가격 : 2,650만원


모델명 : 현대 뉴 투싼 ix 수소(Fuel Cell) 2WD 기본형
연식 : 2016년 02월 (16년식)
주행거리 : 45,000km
지역 : 경기
가격 : 1,350만원


모델명 : 르노삼성 뉴SM3 SE
연식 : 2013년 08월 (14년식)
주행거리 : 65,864km
지역 : 경기
가격 : 650만원


모델명 : 기아 쏘렌토R 디젤 2.0 2WD TLX 프리미엄
연식 : 2011년 01월 (11년식)
주행거리 : 117,741km
지역 : 서울
가격 : 850만원


모델명 : 현대 싼타페 CM 2WD(2.0 VGT) SLX 디럭스
연식 : 2009년 06월 (09년식)
주행거리 : 154,154km
지역 : 경기
가격 : 659만원


------------ page 2 ------------


인증 및 진단 매물
--------------------------------------------------------
모델명 : 기아 더 뉴 레이 1.0 가솔린 프레스티지
연식 : 2018년 06월 (18년식)
주행거리 : 14,000km
지역 : 경기
가격 : 1,150 만원


모델명 : 현대 그랜저IG 렌터카 2.4 가솔린 모던 베이직 기본형
연식 : 2017년 07월 (18년식)
주행거리 : 51,000km
지역 : 경기
가격 : 2,090 만원


모델명 : 현대 올 뉴 투싼 디젤(e-VGT UⅡ)1.7 2WD 모던
연식 : 2017년 02월 (17년식)
주행거리 : 42,287km
지역 : 경기
가격 : 1,750 만원


모델명 : 현대 LF쏘나타 2.0 스타일 스페셜
연식 : 2017년 02월 (17년식)
주행거리 : 59,652km
지역 : 부산
가격 : 1,530 만원


모델명 : 현대 쏘나타 (DN8) 2.0 인스퍼레이션
연식 : 2019년 06월 (20년식)
주행거리 : 52,240km
지역 : 인천
가격 : 2,680 만원




추천 매물
--------------------------------------------------------
모델명 : 르노삼성 뉴SM5(신형) LE
연식 : 2010년 03월 (10년식)
주행거리 : 138,263km
지역 : 경기
가격 : 320만원


모델명 : 기아 올 뉴 K3 1.6 가솔린 트렌디
연식 : 2018년 05월 (19년식)
주행거리 : 97,275km
지역 : 경기
가격 : 1,350만원


모델명 : 르노삼성 QM3 RE 시그니처
연식 : 2016년 04월 (16년식)
주행거리 : 56,491km
지역 : 경기
가격 : 1,180만원


모델명 : 쌍용 코란도C 클러비 2WD 파크
연식 : 2012년 08월 (12년식)
주행거리 : 155,736km
지역 : 경기
가격 : 550만원


모델명 : 현대 포터2 초장축 더블캡 CRDi Modern
연식 : 2019년 10월 (20년식)
주행거리 : 25,590km
지역 : 울산
가격 : 1,890만원




일반 매물
--------------------------------------------------------
모델명 : 르노삼성 뉴SM5 LPLi LE
연식 : 2007년 01월 (07년식)
주행거리 : 167,859km
지역 : 경기
가격 : 180만원


모델명 : 현대 싼타페 2.0 디젤 2WD GOLD 고급형
연식 : 2001년 07월 (01년식)
주행거리 : 193,659km
지역 : 경기
가격 : 190만원


모델명 : 현대 그랜드스타렉스 12인승 왜건 CVX 럭셔리
연식 : 2007년 08월 (08년식)
주행거리 : 149,316km
지역 : 서울
가격 : 690만원


모델명 : 현대 그랜저HG HG300 노블
연식 : 2011년 03월 (11년식)
주행거리 : 111,783km
지역 : 경기
가격 : 1,129만원


모델명 : 현대 싼타페 DM R2.2 2WD PREMIUM
연식 : 2014년 02월 (14년식)
주행거리 : 114,992km
지역 : 경기
가격 : 1,549만원


모델명 : 르노삼성 SM6 1.5 dCi SE
연식 : 2016년 11월 (16년식)
주행거리 : 58,158km
지역 : 경기
가격 : 1,599만원


모델명 : 기아 봉고3 1톤 냉동탑차 초장축 경제형 킹캡 디럭스
연식 : 2015년 01월 (15년식)
주행거리 : 188,707km
지역 : 경남
가격 : 870만원


모델명 : 기아 그랜드카니발 GLX 월드스페셜
연식 : 2005년 08월 (06년식)
주행거리 : 257,561km
지역 : 부산
가격 : 299만원


모델명 : 기아 아벨라 델타 1.3 Si
연식 : 1997년 06월 (97년식)
주행거리 : 160,034km
지역 : 경남
가격 : 200만원


모델명 : 기아 그랜드카니발 GLX 월드스페셜
연식 : 2009년 10월 (10년식)
주행거리 : 164,812km
지역 : 서울
가격 : 790만원


모델명 : 현대 그랜저TG Q270 Luxury 기본형
연식 : 2006년 10월 (07년식)
주행거리 : 155,827km
지역 : 경기
가격 : 270만원


모델명 : 현대 뉴카운티 장축 GOLD 25인승 자가용
연식 : 2014년 02월 (14년식)
주행거리 : 134,000km
지역 : 광주
가격 : 2,999만원


모델명 : 쌍용 코란도C 클러비 2WD 파크
연식 : 2013년 01월 (13년식)
주행거리 : 185,410km
지역 : 대구
가격 : 530만원


모델명 : 현대 더 뉴 아반떼 1.6 GDi 모던 기본형
연식 : 2013년 08월 (14년식)
주행거리 : 54,734km
지역 : 대구
가격 : 750만원


모델명 : 현대 투싼ix 디젤 2WD X20 럭셔리
연식 : 2010년 04월 (11년식)
주행거리 : 128,634km
지역 : 대구
가격 : 699만원


모델명 : 기아 올 뉴 카니발 9인승 2.2 디젤 하이리무진 럭셔리
연식 : 2015년 04월 (15년식)
주행거리 : 93,228km
지역 : 경남
가격 : 2,650만원


모델명 : 현대 뉴 투싼 ix 수소(Fuel Cell) 2WD 기본형
연식 : 2016년 02월 (16년식)
주행거리 : 45,000km
지역 : 경기
가격 : 1,350만원


모델명 : 르노삼성 뉴SM3 SE
연식 : 2013년 08월 (14년식)
주행거리 : 65,864km
지역 : 경기
가격 : 650만원


모델명 : 기아 쏘렌토R 디젤 2.0 2WD TLX 프리미엄
연식 : 2011년 01월 (11년식)
주행거리 : 117,741km
지역 : 서울
가격 : 850만원


모델명 : 현대 싼타페 CM 2WD(2.0 VGT) SLX 디럭스
연식 : 2009년 06월 (09년식)
주행거리 : 154,154km
지역 : 경기
가격 : 659만원

## KB차차차 세부정보 크롤링

In [ ]:
url = 'https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page=1&sort=-orderDate'
driver.get(url)
soup = bs(driver.page_source, 'html.parser')
href_selector = 'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type(1) > div.con.owl-carousel.swiper-area06 > .item > a.link'
href = soup.select_one(href_selector)
print('내부 주소 :', 'https://www.kbchachacha.com' + href['href'])

inner_url = 'https://www.kbchachacha.com' + href['href']
driver.get(inner_url)
soup = bs(driver.page_source, 'html.parser')
selector = 'div.detail-info-list > div.detail-info01'
inner = soup.select_one(selector)

내부 주소 : https://www.kbchachacha.com/public/car/detail.kbc?carSeq=21846463

In [ ]:
inner_url = 'https://www.kbchachacha.com' + href['href']
driver.get(inner_url)
soup = bs(driver.page_source, 'html.parser')
selector = 'div.detail-info-list > div.detail-info01'
inner = soup.select('table')
table_html = str(inner)
table_df_list = pd.read_html(table_html)
table_df = table_df_list[0]

table_df[0].values
table_df[1].values


test_df = []
for i in range(4):
    test_df.append(table_df[i])

In [ ]:
from pandas import DataFrame

In [ ]:
table_df.drop([6]).reindex(range(12), method='bfill')

       0         1     2             3
0   차량정보   51하2687    연식  18년06월(19년형)
1   주행거리  50,000km    연료           가솔린
2    변속기        오토    연비         8.3Km
3     차종        대형   배기량       3,778cc
4     색상       보라색  세금미납            없음
5     압류        없음    저당            없음
6    NaN       NaN   NaN           NaN
7    NaN       NaN   NaN           NaN
8    NaN       NaN   NaN           NaN
9    NaN       NaN   NaN           NaN
10   NaN       NaN   NaN           NaN
11   NaN       NaN   NaN           NaN

In [ ]:
for i in range(1, 2):
  url = f'https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page={i}&sort=-orderDate'
  driver.get(url)
  soup = BeautifulSoup(driver.page_source, 'html.parser')
 
  inner_list = []

  for x in range(1, 6) :
    href_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({x}) > div.con.owl-carousel.swiper-area06 > .item > a.link'
    href = soup.select_one(href_selector)
    inner_url = 'https://www.kbchachacha.com' + href['href']
    
    inner_list.append(inner_url)

  for a in inner_list:

    driver.get(a)
    soup = bs(driver.page_source, 'html.parser')
    selector = 'div.detail-info-list > div.detail-info01'
    inner = soup.select('table')
    table_html = str(inner)
    table_df_list = pd.read_html(table_html)
    table_df = table_df_list[0]

    print(table_df)

      0         1         2             3
0  차량정보  224주1726        연식  20년10월(21년형)
1  주행거리   9,000km        연료           가솔린
2   변속기        오토        연비          정보없음
3    차종        대형       배기량       2,497cc
4    색상       검정색      세금미납            없음
5    압류        없음        저당            없음
6  제시번호  20210826  20210826      20210826
      0         1         2             3
0  차량정보   38호5487        연식  19년03월(19년형)
1  주행거리  12,153km        연료           가솔린
2   변속기        오토        연비        12.8Km
3    차종       SUV       배기량       1,591cc
4    색상       파랑색      세금미납            없음
5    압류        없음        저당            없음
6  제시번호  20210906  20210906      20210906
      0           1           2             3
0  차량정보     40거0273          연식  16년05월(16년형)
1  주행거리   125,903km          연료            디젤
2   변속기          오토          연비        11.6Km
3    차종         SUV         배기량       2,157cc
4    색상          흰색        세금미납            없음
5    압류          없음          저당            없음
6  제시번호  2021061144  2021061144    2021061144
      0             1             2             3
0  차량정보      128보4676            연식  18년04월(19년형)
1  주행거리      67,170km            연료            디젤
2   변속기            오토            연비        13.3Km
3    차종           SUV           배기량       2,199cc
4    색상            흰색          세금미납            없음
5    압류            없음            저당           1 건
6  제시번호  212691051773  212691051773  212691051773
      0         1     2             3
0  차량정보  269우7769    연식  20년06월(21년형)
1  주행거리   8,571km    연료            디젤
2   변속기        오토    연비          정보없음
3    차종       SUV   배기량           0cc
4    색상        흰색  세금미납            없음
5    압류        없음    저당           1 건
6  제시번호      3348  3348          3348

In [ ]:
for i in range(0, 2):
  url = f'https://www.kbchachacha.com/public/search/main.kbc#!?countryOrder=1&page={i}&sort=-orderDate'
  driver.get(url)
  soup = BeautifulSoup(driver.page_source, 'html.parser')

  print(f'------------ page {i + 1} ------------')
  print("\n") 

  # 인증 및 진단 매물
  print("인증 및 진단 매물")
  print("--------------------------------------------------------")
  for j in range(1, 100):
    name_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.tit'
    name = soup.select(name_selector)
    if not name :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in name[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('모델명 :', text)

    pay_selector = f'div.__used-car-list > div:nth-of-type(1) > div.list-in > div:nth-of-type({j}) > div.con.owl-carousel.swiper-area06 > .item > a.link > strong.pay'
    pay = soup.select(pay_selector)
    if not pay :
      break
    target_text_without_child_tags = [
      bs_object
      for bs_object
      in pay[0]
      if isinstance(bs_object, NavigableString)
    ]

    text = "".join(target_text_without_child_tags).strip()
    print('가격 :', text, '만원')
    print("\n")