# Import

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import preprocessing
from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingRegressor
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC 
from sklearn.ensemble import VotingClassifier, BaggingClassifier, RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import plot_roc_curve

# 중고차 데이터

In [ ]:
file_path = '/content/drive/MyDrive/kb차차차/최종 데이터.csv'

In [ ]:
df = pd.read_csv(file_path, engine = 'python', encoding = 'cp949')

In [ ]:
df = df.drop(columns = ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18'])
df

        제조사       모델    차종  가격(만원)    연식  주행거리(km)   연료 변속기  연비(km)  배기량(cc)
0        기아       모닝    경차     210  2008    100000  가솔린  오토     0.0    991.0
1        쌍용      티볼리   SUV    1860  2019      4427  가솔린  오토    12.0   4427.0
2        현대  제네시스 쿠페  스포츠카     870  2010    142395  가솔린  오토     0.0   3778.9
3      제네시스    BH330    대형     990  2009    171709  가솔린  오토     0.0   3300.0
4        현대     제네시스    대형     990  2009    171709  가솔린  오토     0.0   3300.0
...     ...      ...   ...     ...   ...       ...  ...  ..     ...      ...
65871    기아     스포티지   SUV     610  2009    134118  가솔린  오토     0.0      0.0
65872    기아     스포티지   SUV     250  2006    290000  가솔린  오토     0.0      0.0
65873    기아     스포티지   SUV     300  2009    238700   디젤  오토    15.0      0.0
65874    기아     스포티지   SUV     350  2006    119506   디젤  오토     0.0      0.0
65875    기아     스포티지   SUV     249  2005    211505   디젤  오토     0.0      0.0

[65876 rows x 10 columns]

# 원핫인코더 중고차 데이터

In [ ]:
test = pd.get_dummies(df)
test

       가격(만원)    연식  주행거리(km)  연비(km)  ...  변속기_SAT  변속기_기타  변속기_수동  변속기_오토
0         210  2008    100000     0.0  ...        0       0       0       1
1        1860  2019      4427    12.0  ...        0       0       0       1
2         870  2010    142395     0.0  ...        0       0       0       1
3         990  2009    171709     0.0  ...        0       0       0       1
4         990  2009    171709     0.0  ...        0       0       0       1
...       ...   ...       ...     ...  ...      ...     ...     ...     ...
65871     610  2009    134118     0.0  ...        0       0       0       1
65872     250  2006    290000     0.0  ...        0       0       0       1
65873     300  2009    238700    15.0  ...        0       0       0       1
65874     350  2006    119506     0.0  ...        0       0       0       1
65875     249  2005    211505     0.0  ...        0       0       0       1

[65876 rows x 193 columns]

# Random Forest

In [ ]:
features = test.loc[:, '연식':'변속기_오토']
X = features.values
y = test['가격(만원)']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
logreg = RandomForestRegressor(oob_score=True, n_jobs=-1, random_state=42)
logreg.fit(X_train, y_train)
print("테스트 점수 : {:.2f}".format(logreg.score(X_test,y_test)))
print("훈련셋 점수 : {:.2f}".format(logreg.score(X_train,y_train)))

테스트 점수 : 0.97
훈련셋 점수 : 1.00

# Gradient Boosting

In [ ]:
features = test.loc[:, '연식':'변속기_오토']
X = features.values
y = test['가격(만원)']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
grad_boost = GradientBoostingRegressor(random_state=42)
cv = cross_validate(estimator=grad_boost, X=X_train, y=y_train, n_jobs=-1, 
                    return_train_score=True)
print(np.mean(cv['train_score']))
print(np.mean(cv['test_score']))

0.9326658610933649
0.9232236568884369

# Poly(degree=3) + Standard + Linear

In [ ]:
poly = PolynomialFeatures(degree=3, include_bias=False) 
std_scaler = StandardScaler()
lin_reg = LinearRegression()

In [ ]:
model = Pipeline(steps=[('deg_2_poly', poly),
                        ('scaler', std_scaler),
                        ('reg', lin_reg)])
model.fit(X_train, y_train)

In [ ]:
train_pred = model.predict(X_train)
r2_score(y_train, train_pred)

In [ ]:
test_pred = model.predict(X_test)
r2_score(y_test, test_pred)

# 머신러닝 비교

In [ ]:
knn_clf = KNeighborsClassifier(n_jobs=-1)
log_clf = LogisticRegression(random_state=42, n_jobs=-1)
sgd_clf = SGDClassifier(loss='log', n_jobs=-1, random_state=42) 
tree_clf = DecisionTreeClassifier(random_state=42)
svm_clf = SVC(probability=True, random_state=42)

In [ ]:
classifiers = [knn_clf, log_clf, sgd_clf, tree_clf, svm_clf]
for clf in classifiers:
    clf.fit(X_train, y_train)  # 모델 훈련
    acc = clf.score(X_test, y_test)  # 테스트 셋 평가 점수(정확도) 계산
    print(clf.__class__.__name__, 'accuracy:', acc)

KNeighborsClassifier accuracy: 0.07377497115793309
LogisticRegression accuracy: 0.012144028174145364
SGDClassifier accuracy: 0.011233226061084461
DecisionTreeClassifier accuracy: 0.21926042868419454